In [1]:
import numpy as np

# Hebbian Learning Rule
def hebbian_learning_rule(input_pattern, weight_matrix):
    return weight_matrix + np.outer(input_pattern, input_pattern)

# Perceptron Learning Rule
def perceptron_learning_rule(input_pattern, target, weight_vector, learning_rate):
    prediction = np.dot(weight_vector, input_pattern)
    error = target - prediction
    return weight_vector + learning_rate * error * input_pattern

# Delta Learning Rule
def delta_learning_rule(input_pattern, target, weight_matrix, learning_rate):
    prediction = np.dot(weight_matrix, input_pattern)
    error = target - prediction
    return weight_matrix + learning_rate * np.outer(error, input_pattern)

# Correlation Learning Rule
def correlation_learning_rule(input_pattern, weight_matrix):
    return weight_matrix + np.outer(input_pattern, input_pattern)

# Out Star Learning Rule
def out_star_learning_rule(input_pattern, weight_matrix, learning_rate):
    return weight_matrix + learning_rate * np.outer(input_pattern, input_pattern)

# Initialize weights with random values
input_size = 3
hebbian_weights = np.random.rand(input_size, input_size)
perceptron_weights = np.random.rand(input_size)
delta_weights = np.random.rand(input_size, input_size)
correlation_weights = np.random.rand(input_size, input_size)
out_star_weights = np.random.rand(input_size, input_size)

print("Hebbian Weights:", hebbian_weights)
print("\nPerceptron Weights:", perceptron_weights)
print("\nDelta Weights:", delta_weights)
print("\nCorrelation Weights:", correlation_weights)
print("\nOut Star Weights:", out_star_weights)

# Sample input and target data
input_pattern = np.array([0.2, 0.5, 0.8])
target = 1

# Apply learning rules
hebbian_weights_updated = hebbian_learning_rule(input_pattern, hebbian_weights)
perceptron_weights_updated = perceptron_learning_rule(input_pattern, target, perceptron_weights, learning_rate=0.1)
delta_weights_updated = delta_learning_rule(input_pattern, target, delta_weights, learning_rate=0.1)
correlation_weights_updated = correlation_learning_rule(input_pattern, correlation_weights)
out_star_weights_updated = out_star_learning_rule(input_pattern, out_star_weights, learning_rate=0.1)

# Display updated weights
print("\nHebbian Updated Weights:", hebbian_weights_updated)
print("\nPerceptron Updated Weights:", perceptron_weights_updated)
print("\nDelta Updated Weights:", delta_weights_updated)
print("\nCorrelation Updated Weights:", correlation_weights_updated)
print("\nOut Star Updated Weights:", out_star_weights_updated)

Hebbian Weights: [[0.75770207 0.97793932 0.40247765]
 [0.27626824 0.5458531  0.40109061]
 [0.63342983 0.19151917 0.82593941]]

Perceptron Weights: [0.26665818 0.23433659 0.51397828]

Delta Weights: [[0.56554047 0.28672249 0.90275812]
 [0.13174521 0.02089043 0.88380856]
 [0.17147318 0.50038481 0.62785448]]

Correlation Weights: [[0.82638525 0.05183879 0.07039659]
 [0.17957817 0.78727131 0.59921633]
 [0.88137276 0.84608234 0.08336776]]

Out Star Weights: [[0.966868   0.32276158 0.86425047]
 [0.78658872 0.75108191 0.10347332]
 [0.41994101 0.93459702 0.92271653]]

Hebbian Updated Weights: [[0.79770207 1.07793932 0.56247765]
 [0.37626824 0.7958531  0.80109061]
 [0.79342983 0.59151917 1.46593941]]

Perceptron Updated Weights: [0.27502453 0.25525246 0.54744368]

Delta Updated Weights: [[0.56596695 0.2877887  0.90446406]
 [0.13686839 0.03369837 0.90430127]
 [0.17573777 0.51104627 0.64491283]]

Correlation Updated Weights: [[0.86638525 0.15183879 0.23039659]
 [0.27957817 1.03727131 0.99921633]
